### ISSUE TITLE
Dateset is not here

### ISSUE THREAD

**Issue by Littlebee1** [ahmed-nady/Real-Time-Abnormal-Event-Detection-in-Crowded-Scenes#1]
Hello, I read your code,while I can not understand the the path in your code ,could you give the dateset in your project,such as test and train ,I have the dataset you have mentioned.But ,I do not divide it into details.

If you could  upload the dataset you mentioned ,Thanks so much.

**Comment by ahmed-nady** [comment]
Hi guy, For the UMN dataset, 
There are three scenes (Lawn,Indoor, Plaza), for each each you take the first 400 frames as training and the rest for testing except the Indoor scene we you the first 300 normal frames. That's it
Also you can look at the research paper at 
https://www.researchgate.net/publication/327972246_REAL-TIME_ABNORMAL_EVENT_DETECTION_IN_CROWDED_SCENES

**Comment by Littlebee1** [comment]
Thank you very much for you replay.I read your paper recently.It mainlyintruduce the global anomalous evnet detection.I want to know if this code is also for local anomalous event detection.

**Comment by Littlebee1** [comment]
There is UCSD dateset in your project,  It is also for UCSD dateset?

**Comment by ahmed-nady** [comment]
yeah, you can extend the global anomalous event detection to local anomalous detection by dividing the frame into cells/regions and repeat the process of global event detection  on each region.
I used UCSD dataset for that.

**Comment by Littlebee1** [comment]
I'm sorry to trouble you again，these days I used this  method for ucsd dateset,while the result of local anomalous event detection is not satisfied .Could you give me some advice，thanks indeed！  ^-^
